FROM node:18-alpine3.14

ENV NODE_ENV=dev

# Create app directory
WORKDIR /app

# Install app dependencies
# A wildcard is used to ensure both package.json AND package-lock.json are copied
# where available (npm@5+)
COPY package*.json ./

RUN npm install --include=dev

# If you are building your code for production
# RUN npm ci --only=production

# Bundle app source
COPY . .

EXPOSE 8080
CMD [ "npm", "run", "devStart" ] #Para dev se usa nodemon para que updatee los cambios
#CMD [ "node", "server.js" ] #produccion node