version: '3.8'

services:

  #DATABASES--------------------------------------------------------------
  db-votos-mongo:
    image: mongo:4.4.14
    ports:
      - 27017:27017 #solo para testing, lo publica hacia fuera
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
  
  #Guarda todos los usuarios ci-hashdelPassword para validar
  db-auth-redis:
    build: './db-auth-redis'
    ports:
      - 6380:6379 #solo para testing, lo publica hacia fuera
  
  #guarda todas las sesiones activas
  db-sessions-redis:
    image: redis:7.0.0
    #build: './db-sessions-redis'
    ports:
      - 6379:6379 #solo para testing, lo publica hacia fuera
  #------------------------------------------------------------------------


  #BACKENDS----------------------------------------------------------------
  backend-voto-node:
    build: './backend-voto-node/app'
    depends_on:
      - db-votos-mongo
      - db-auth-redis
    ports: 
      - 8080:8080
    volumes:
       - './backend-voto-node/app:/app'

  backend-corte-node:
    build: './backend-corte-node/app'
    depends_on:
      - db-votos-mongo
      - db-auth-redis
    ports: 
      - 8081:8080
    volumes:
       - './backend-corte-node/app:/app'

  #------------------------------------------------------------------------


  #OPCIONALES--------------------------------------------------------------
  #gestor de mongodb - para testing
  mongo-express:
    image: mongo-express
    ports:
      - 8082:8081 #solo para testing
    depends_on:
      - db-votos-mongo
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: root
      ME_CONFIG_MONGODB_URL: mongodb://root:root@db-votos-mongo:27017/
  #------------------------------------------------------------------------

